#!/bin/bash

STYLE=$(git config --get hooks.clangformat.style)
if [ -n "${STYLE}" ] ; then
  STYLEARG="-style=${STYLE}"
else
  STYLEARG=""
fi

format_file() {
  file="${1}"
  clang-format -extensions c,h,cpp,hpp,cc -i ${STYLEARG} ${1}
  git add ${1}
}

case "${1}" in
  --about )
    ;;
  * )
    echo "Runs clang-format on source files:"
    for file in `git diff-index --cached --name-only HEAD` ; do
      echo -e "  \033[32m${file}\033[0m"
      format_file "${file}"
    done
    ;;
esac